workspace:
  base: /go
  path: src/github.com/jmlambert78/contrelease
pipeline:
  backend:
    image: golang
    commands:
      - go get
      - go build
      - go test
      - contrelease
      - go run
      -curl localhost:8080
services:
  mongo:
    image: mongo:3.0
    command: [ --smallfiles ]
