language: go
sudo: required
services:
- docker
addons:
  ssh_known_hosts: 46.38.251.201
env:
- DOCKER_IMAGE_NAME="jmlambert78/contrel:$TRAVIS_BUILD_NUMBER"

script: go build -o main

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 
- docker build -t $DOCKER_IMAGE_NAME .
- docker push $DOCKER_IMAGE_NAME

